const API_BASE = window.SIH_API_URL || '';
let currentUser; let studentData; let adminData; let teamsCache = []; let resourcesCache = []; let charts = {};

function api(path) { return `${API_BASE}${path}`; }
function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[char]); }
function avatarUrl(user = {}) { return user.photoUrl || `https://ui-avatars.com/api/?background=0756a4&color=fff&name=${encodeURIComponent(user.fullName || 'SIH')}`; }
function initials(value = '') { return value.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase(); }
function formatDate(value, withTime = false) { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'To be announced' : date.toLocaleString('en-IN', withTime ? { dateStyle: 'medium', timeStyle: 'short' } : { day: 'numeric', month: 'short', year: 'numeric' }); }
function formatLocalInput(value) { const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0, 16); }
function statusLabel(value = 'pending') { return value.replace(/_/g, ' '); }
function statusBadge(value = 'pending') { return `<span class="badge-status ${escapeHtml(value)}">${escapeHtml(statusLabel(value))}</span>`; }

function token() { return localStorage.getItem('sih_token'); }
async function request(path, options = {}) {
  const headers = { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}), Authorization: `Bearer ${token()}` };
  const response = await fetch(api(path), { ...options, headers });
  if (response.status === 401) { localStorage.removeItem('sih_token'); localStorage.removeItem('sih_user'); window.location.href = 'index.html'; throw new Error('Your session has expired.'); }
  const contentType = response.headers.get('content-type') || '';
  const payload = contentType.includes('application/json') ? await response.json() : null;
  if (!response.ok) throw new Error(payload?.message || 'The request could not be completed.');
  return payload;
}
function toast(text, kind = 'success') { const id = `toast-${Date.now()}`; const root = document.getElementById('toasts'); root.insertAdjacentHTML('beforeend', `<div id="${id}" class="toast align-items-center text-bg-${kind === 'error' ? 'danger' : 'success'} border-0" role="alert"><div class="d-flex"><div class="toast-body">${escapeHtml(text)}</div><button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div></div>`); const instance = new bootstrap.Toast(document.getElementById(id), { delay: 3500 }); instance.show(); }
function setUserChrome() { document.getElementById('sidebar-name').textContent = currentUser.fullName; document.getElementById('sidebar-role').textContent = currentUser.role === 'admin' ? 'Administrator' : 'Student portal'; document.getElementById('top-avatar').src = avatarUrl(currentUser); document.getElementById('dash-title').textContent = currentUser.role === 'admin' ? 'SIH command centre' : `Hello, ${currentUser.fullName.split(' ')[0]}`; document.getElementById('dash-kicker').textContent = currentUser.role === 'admin' ? 'Secure administrator workspace' : 'Your SIH 2026 workspace'; }

function changeView(view) {
  document.querySelectorAll('.dashboard-view').forEach((section) => section.classList.toggle('active', section.id === `view-${view}`));
  document.querySelectorAll('#side-nav button').forEach((button) => button.classList.toggle('active', button.dataset.view === view));
  if (currentUser.role === 'student') {
    if (view === 'profile') renderProfile(); if (view === 'team') renderTeam(); if (view === 'notifications') renderNotifications();
  } else {
    if (view === 'students') loadStudents(); if (view === 'teams') loadTeams(); if (view === 'evaluation') loadEvaluation(); if (view === 'resources') loadResources(); if (view === 'settings') loadSettings(); if (view === 'activity') loadActivity();
  }
}

function renderStudentOverview() {
  const { user, team, settings, announcements } = studentData;
  document.getElementById('student-status-card').innerHTML = `<img class="avatar" src="${escapeHtml(avatarUrl(user))}" alt="${escapeHtml(user.fullName)}"><div><h2>${escapeHtml(user.fullName)}</h2><p>${escapeHtml(user.department)} · ${escapeHtml(user.academicYear)} · Profile ${statusLabel(user.registrationStatus)}</p></div><div class="ms-lg-auto">${statusBadge(user.registrationStatus)}</div>`;
  const teamBadge = document.getElementById('student-team-badge');
  teamBadge.className = `badge-status ${team?.status || 'pending'}`;
  teamBadge.textContent = statusLabel(team?.status || 'pending');
  const progress = [ ['Profile', user.registrationStatus === 'approved' ? 'Verified' : 'Submitted'], ['Team', team ? team.name : 'Not registered'], ['Selected PS', team ? team.problem.psId : 'Choose a team first'] ];
  document.getElementById('student-progress').innerHTML = progress.map(([key, value]) => `<div><span>${escapeHtml(key)}</span><b>${escapeHtml(value)}</b></div>`).join('');
  const openDate = new Date(settings.registrationEnabled ? settings.registrationClose : settings.registrationOpen); const days = Math.max(0, Math.ceil((openDate - Date.now()) / 86400000));
  document.getElementById('student-countdown').innerHTML = `<strong>${settings.registrationEnabled ? 'Registration closes soon' : 'Registration opens soon'}</strong><span>${days} day${days === 1 ? '' : 's'} · ${formatDate(openDate)}</span>`;
  document.getElementById('student-notices').innerHTML = (announcements || []).slice(0, 3).map(noticeItem).join('') || '<div class="empty-state"><strong>All clear</strong><span>No notices have been published yet.</span></div>';
}
function noticeItem(notice) { return `<div class="dash-list-item"><div class="activity-icon">!</div><div class="activity-text"><strong>${escapeHtml(notice.title)}</strong><span>${escapeHtml(notice.message)}</span></div></div>`; }

function renderProfile() {
  const user = studentData.user;
  document.getElementById('profile-content').innerHTML = `<div class="profile-hero"><img class="avatar" src="${escapeHtml(avatarUrl(user))}" alt="${escapeHtml(user.fullName)}"><div><h2>${escapeHtml(user.fullName)}</h2><p>${escapeHtml(user.registrationNumber)} · ${escapeHtml(user.department)} · ${escapeHtml(user.branch)}</p></div><div class="ms-lg-auto">${statusBadge(user.registrationStatus)}</div></div><div class="row g-3 mt-1"><div class="col-xl-7"><div class="dash-card"><div class="dash-heading"><h2>Team leader profile</h2></div><div class="detail-grid"><div><span>Email</span><b>${escapeHtml(user.email)}</b></div><div><span>Mobile</span><b>${escapeHtml(user.mobile)}</b></div><div><span>Gender</span><b>${escapeHtml(user.gender)}</b></div><div><span>Academic year</span><b>${escapeHtml(user.academicYear)} · Sem ${escapeHtml(user.semester)}</b></div><div><span>Registration number</span><b>${escapeHtml(user.registrationNumber)}</b></div><div><span>Roll number</span><b>${escapeHtml(user.rollNumber)}</b></div></div></div></div><div class="col-xl-5"><form id="profile-form" class="form-panel" enctype="multipart/form-data"><h2>Update contact details</h2><p class="small text-secondary">Academic details are controlled by the SIH cell.</p><label class="form-label mt-2">Mobile</label><input class="form-control" name="mobile" value="${escapeHtml(user.mobile)}" required><label class="form-label mt-3">New photo <span class="text-secondary">(optional)</span></label><input class="form-control" type="file" name="photo" accept="image/png,image/jpeg,image/webp"><button class="btn btn-primary mt-3" type="submit">Save changes</button></form></div></div>`;
  document.getElementById('profile-form').addEventListener('submit', updateProfile);
}
async function updateProfile(event) { event.preventDefault(); try { const data = await request('/api/student/profile', { method: 'PUT', body: new FormData(event.currentTarget) }); studentData.user = data.user; currentUser = data.user; setUserChrome(); renderProfile(); toast(data.message); } catch (error) { toast(error.message, 'error'); } }

function memberTemplate(index, member = {}) {
  return `<div class="member-form" data-member><h4>Member ${index + 1}${index === 0 ? ' · Team leader' : ''}</h4>${index ? '<button class="dashboard-btn danger remove-member" type="button">Remove</button>' : ''}<div class="row g-2"><div class="col-md-6"><label class="form-label">Name *</label><input class="form-control form-control-sm" name="name" value="${escapeHtml(member.name || '')}" required></div><div class="col-md-3"><label class="form-label">Gender *</label><select class="form-select form-select-sm" name="gender" required><option value="">Select</option>${['Male','Female','Other','Prefer not to say'].map((value) => `<option ${member.gender === value ? 'selected' : ''}>${value}</option>`).join('')}</select></div><div class="col-md-3"><label class="form-label">Role / skill</label><input class="form-control form-control-sm" name="roleSkill" value="${escapeHtml(member.roleSkill || '')}"></div><div class="col-md-6"><label class="form-label">Email *</label><input class="form-control form-control-sm" type="email" name="email" value="${escapeHtml(member.email || '')}" required></div><div class="col-md-6"><label class="form-label">Mobile *</label><input class="form-control form-control-sm" name="mobile" value="${escapeHtml(member.mobile || '')}" required></div><div class="col-md-4"><label class="form-label">Branch *</label><input class="form-control form-control-sm" name="branch" value="${escapeHtml(member.branch || '')}" required></div><div class="col-md-4"><label class="form-label">Academic year *</label><input class="form-control form-control-sm" name="academicYear" value="${escapeHtml(member.academicYear || '')}" required></div><div class="col-md-4"><label class="form-label">Registration No.</label><input class="form-control form-control-sm" name="registrationNumber" value="${escapeHtml(member.registrationNumber || '')}"></div></div></div>`;
}
function problemOptions() { return (studentData.problems || []).map((problem) => `<option value="${escapeHtml(problem.psId)}">${escapeHtml(problem.psId)} · ${escapeHtml(problem.track)} · ${escapeHtml(problem.title)}</option>`).join(''); }
function renderTeam() {
  const { team, user } = studentData;
  if (team) { document.getElementById('team-content').innerHTML = `<div class="dash-card"><div class="dash-heading"><div><p class="section-kicker mb-1">Your submitted team</p><h2>${escapeHtml(team.name)}</h2></div>${statusBadge(team.status)}</div><div class="team-summary"><div><span>Challenge</span><b>${escapeHtml(team.problem.psId)}</b></div><div><span>Track</span><b>${escapeHtml(team.problem.track)}</b></div><div><span>Faculty mentor</span><b>${escapeHtml(team.facultyMentor)}</b></div></div><div class="mt-4"><h3 class="h6">${escapeHtml(team.problem.title)}</h3><p class="small text-secondary">${escapeHtml(team.adminNote || 'Your team is awaiting review by the SIH cell.')}</p></div><div class="dash-heading mt-4"><h2>Team members · ${team.members.length}/5</h2></div><div class="team-members">${team.members.map((member, index) => `<div class="team-member"><i>${index + 1}</i><div><b>${escapeHtml(member.name)}${index === 0 ? ' · Leader' : ''}</b><span>${escapeHtml(member.branch)} · ${escapeHtml(member.academicYear)} · ${escapeHtml(member.email)}</span></div></div>`).join('')}</div></div>`; return; }
  document.getElementById('team-content').innerHTML = `<div class="dash-card empty-state"><strong>Team record unavailable</strong><span>Team registration is completed before the leader signs in. Please contact the SIH Cell on WhatsApp for help.</span></div>`;
}
function bindRemoveMembers() { document.querySelectorAll('.remove-member').forEach((button) => button.onclick = () => { button.closest('[data-member]').remove(); document.querySelectorAll('[data-member]').forEach((item, index) => item.querySelector('h4').textContent = `Member ${index + 1}`); }); }
async function createTeam(event) { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); body.members = [...form.querySelectorAll('[data-member]')].map((box) => Object.fromEntries([...box.querySelectorAll('input,select')].map((input) => [input.name, input.value]))); try { const data = await request('/api/student/team', { method: 'POST', body: JSON.stringify(body) }); studentData.team = data.team; toast(data.message); renderStudentOverview(); renderTeam(); } catch (error) { toast(error.message, 'error'); } }
function renderNotifications() { document.getElementById('notifications-content').innerHTML = studentData.announcements?.map(noticeItem).join('') || '<div class="empty-state"><strong>All clear</strong><span>No notifications have been published yet.</span></div>'; }

function statCard(label, value, note, color = '') { return `<article class="stat-card ${color}"><p>${escapeHtml(label)}</p><strong>${escapeHtml(value)}</strong><small>${escapeHtml(note)}</small></article>`; }
async function loadAdminDashboard() { adminData = await request('/api/admin/dashboard'); const stats = adminData.stats; document.getElementById('admin-stats').innerHTML = [statCard('Total students', stats.totalStudents, `${stats.statuses.approved || 0} approved`), statCard('Total teams', stats.totalTeams, `${stats.tracks.Software || 0} software teams`, 'green'), statCard('Pending students', stats.statuses.pending || 0, 'Awaiting review', 'orange'), statCard('Qualified teams', stats.qualifiedTeams || 0, 'Ready for nomination', 'green')].join('');
  document.getElementById('recent-teams').innerHTML = adminData.recentTeams.map((team) => `<tr><td><b>${escapeHtml(team.name)}</b></td><td>${escapeHtml(team.leader?.fullName || '-')}</td><td>${escapeHtml(team.problem.psId)}</td><td>${statusBadge(team.status)}</td></tr>`).join('') || '<tr><td colspan="4" class="text-secondary">No team registrations yet.</td></tr>';
  document.getElementById('recent-activity').innerHTML = adminData.recentActivity.map(activityItem).join('') || '<div class="empty-state"><strong>No activity yet</strong><span>Actions will be recorded here.</span></div>';
  renderCharts(stats);
}
function renderCharts(stats) { if (!window.Chart) return; Object.values(charts).forEach((chart) => chart.destroy()); const dailyLabels = stats.daily.map((row) => row._id); const dailyValues = stats.daily.map((row) => row.count); charts.daily = new Chart(document.getElementById('registration-chart'), { type: 'line', data: { labels: dailyLabels.length ? dailyLabels : ['No data'], datasets: [{ label: 'Students', data: dailyValues.length ? dailyValues : [0], borderColor: '#0756a4', backgroundColor: 'rgba(7,86,164,.12)', fill: true, tension: .35, pointBackgroundColor: '#0a873f' }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { y: { beginAtZero: true, ticks: { precision: 0 } } } } }); charts.track = new Chart(document.getElementById('track-chart'), { type: 'doughnut', data: { labels: ['Software', 'Hardware'], datasets: [{ data: [stats.tracks.Software || 0, stats.tracks.Hardware || 0], backgroundColor: ['#0756a4','#0a873f'], borderWidth: 0 }] }, options: { responsive: true, maintainAspectRatio: false, cutout: '68%', plugins: { legend: { position: 'bottom', labels: { usePointStyle: true } } } } }); }
function activityItem(item) { return `<div class="dash-list-item"><div class="activity-icon">✓</div><div class="activity-text"><strong>${escapeHtml(item.action)}</strong><span>${escapeHtml(item.detail || item.actor?.fullName || 'System')} · ${formatDate(item.createdAt, true)}</span></div></div>`; }

async function loadStudents(page = 1) { try { const search = document.getElementById('student-search').value; const status = document.getElementById('student-status-filter').value; const data = await request(`/api/admin/students?page=${page}&search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`); document.getElementById('student-table').innerHTML = data.students.map((student) => `<tr><td><div class="mini-user"><img class="avatar" src="${escapeHtml(avatarUrl(student))}" alt=""><span>${escapeHtml(student.fullName)}<small class="d-block text-secondary fw-normal">${escapeHtml(student.registrationNumber)}</small></span></div></td><td>${escapeHtml(student.email)}<small class="d-block text-secondary">${escapeHtml(student.mobile)}</small></td><td>${escapeHtml(student.department)}<small class="d-block text-secondary">${escapeHtml(student.academicYear)}</small></td><td>${escapeHtml(student.team?.problem?.psId || '—')}<small class="d-block text-secondary">${escapeHtml(student.team?.name || 'No team')}</small></td><td>${statusBadge(student.registrationStatus)}</td><td class="text-nowrap"><button class="dashboard-btn success student-status" data-id="${student.id}" data-status="approved">Approve</button> <button class="dashboard-btn danger student-status" data-id="${student.id}" data-status="rejected">Reject</button> <button class="dashboard-btn danger student-delete" data-id="${student.id}">Delete</button></td></tr>`).join('') || '<tr><td colspan="6" class="text-secondary">No students found.</td></tr>'; document.getElementById('student-pagination').textContent = `${data.total} record${data.total === 1 ? '' : 's'} · Page ${data.page} of ${data.pages || 1}`; document.querySelectorAll('.student-status').forEach((button) => button.onclick = () => changeStudentStatus(button.dataset.id, button.dataset.status)); document.querySelectorAll('.student-delete').forEach((button) => button.onclick = () => deleteStudent(button.dataset.id)); } catch (error) { toast(error.message, 'error'); } }
async function changeStudentStatus(id, status) { try { const data = await request(`/api/admin/students/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); toast(data.message); loadStudents(); loadAdminDashboard(); } catch (error) { toast(error.message, 'error'); } }
async function deleteStudent(id) { if (!window.confirm('Delete this student and any leader-owned team? This cannot be undone.')) return; try { const data = await request(`/api/admin/students/${id}`, { method: 'DELETE' }); toast(data.message); loadStudents(); loadAdminDashboard(); } catch (error) { toast(error.message, 'error'); } }

async function loadTeams() { try { const data = await request('/api/admin/teams'); teamsCache = data.teams; document.getElementById('team-table').innerHTML = teamsCache.map((team) => `<tr><td><b>${escapeHtml(team.name)}</b></td><td>${escapeHtml(team.leader?.fullName || '-')}<small class="d-block text-secondary">${escapeHtml(team.leader?.department || '')}</small></td><td>${escapeHtml(team.problem.psId)}<small class="d-block text-secondary">${escapeHtml(team.problem.track)}</small></td><td>${team.members.length}/5</td><td><input class="form-control form-control-sm mentor-input" data-id="${team._id}" value="${escapeHtml(team.facultyMentor)}"></td><td><select class="form-select form-select-sm team-status-input" data-id="${team._id}">${['pending','approved','rejected','revision_required','qualified'].map((status) => `<option value="${status}" ${team.status === status ? 'selected' : ''}>${statusLabel(status)}</option>`).join('')}</select></td><td class="text-nowrap"><button class="dashboard-btn save-team" data-id="${team._id}">Save</button> <button class="dashboard-btn authorization" data-id="${team._id}">Letter</button></td></tr>`).join('') || '<tr><td colspan="7" class="text-secondary">No teams registered.</td></tr>'; document.querySelectorAll('.save-team').forEach((button) => button.onclick = () => updateTeam(button.dataset.id)); document.querySelectorAll('.authorization').forEach((button) => button.onclick = () => downloadFile(`/api/admin/authorization/${button.dataset.id}`, `sih-authorization-${button.dataset.id}.pdf`)); } catch (error) { toast(error.message, 'error'); } }
async function updateTeam(id) { const mentor = document.querySelector(`.mentor-input[data-id="${id}"]`).value; const status = document.querySelector(`.team-status-input[data-id="${id}"]`).value; try { const data = await request(`/api/admin/teams/${id}`, { method: 'PATCH', body: JSON.stringify({ facultyMentor: mentor, status }) }); toast(data.message); loadTeams(); } catch (error) { toast(error.message, 'error'); } }

async function loadEvaluation() { try { if (!teamsCache.length) { const data = await request('/api/admin/teams'); teamsCache = data.teams; } document.getElementById('evaluation-team').innerHTML = '<option value="">Select a team</option>' + teamsCache.map((team) => `<option value="${team._id}">${escapeHtml(team.name)} · ${escapeHtml(team.problem.psId)}</option>`).join(''); await loadRanking(); } catch (error) { toast(error.message, 'error'); } }
function updateScoreTotal() { const values = [...document.querySelectorAll('#evaluation-form input[type="number"]')].map((input) => Number(input.value || 0)); document.getElementById('score-total').textContent = values.reduce((total, value) => total + value, 0); }
async function submitEvaluation(event) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const teamId = values.teamId; delete values.teamId; const scores = {}; ['problemUnderstanding','innovation','technicalFeasibility','prototypeReadiness','impact','presentation'].forEach((key) => { scores[key] = Number(values[key]); delete values[key]; }); try { const data = await request(`/api/admin/evaluations/${teamId}`, { method: 'PUT', body: JSON.stringify({ ...values, scores }) }); toast(data.message); await loadRanking(); loadTeams(); } catch (error) { toast(error.message, 'error'); } }
async function loadRanking() { try { const data = await request('/api/admin/evaluations/ranking'); document.getElementById('ranking-table').innerHTML = data.ranking.map((row) => `<tr><td><b>${row.rank}</b></td><td>${escapeHtml(row.team.name)}<small class="d-block text-secondary">${escapeHtml(row.team.problem.psId)}</small></td><td><b>${row.averageScore}</b>/100</td><td>${row.judges}</td></tr>`).join('') || '<tr><td colspan="4" class="text-secondary">No evaluations saved yet.</td></tr>'; } catch (error) { toast(error.message, 'error'); } }

async function loadResources() { try { const data = await request('/api/admin/resources'); resourcesCache = data.resources; document.getElementById('admin-resource-list').innerHTML = resourcesCache.map((resource) => `<div class="dash-list-item"><div class="activity-icon">PDF</div><div class="activity-text flex-grow-1"><strong>${escapeHtml(resource.title)}</strong><span>${escapeHtml(resource.category || 'Resource')} · ${resource.isPublic === false ? 'Private' : 'Student-visible'}</span></div>${resource._id ? `<button class="dashboard-btn danger remove-resource" data-id="${resource._id}">Delete</button>` : '<span class="small text-secondary">Default</span>'}</div>`).join(''); document.querySelectorAll('.remove-resource').forEach((button) => button.onclick = () => removeResource(button.dataset.id)); } catch (error) { toast(error.message, 'error'); } }
async function submitResource(event) { event.preventDefault(); const form = event.currentTarget; const formData = new FormData(form); formData.set('isPublic', formData.has('isPublic') ? 'true' : 'false'); try { const data = await request('/api/admin/resources', { method: 'POST', body: formData }); form.reset(); toast(data.message); loadResources(); } catch (error) { toast(error.message, 'error'); } }
async function removeResource(id) { if (!window.confirm('Remove this resource?')) return; try { const data = await request(`/api/admin/resources/${id}`, { method: 'DELETE' }); toast(data.message); loadResources(); } catch (error) { toast(error.message, 'error'); } }
async function submitAnnouncement(event) { event.preventDefault(); try { const data = await request('/api/admin/announcements', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); event.currentTarget.reset(); toast(data.message); } catch (error) { toast(error.message, 'error'); } }

async function loadSettings() { try { const data = await request('/api/admin/settings'); const form = document.getElementById('settings-form'); Object.entries(data.settings).forEach(([key, value]) => { if (!form.elements[key]) return; if (form.elements[key].type === 'checkbox') form.elements[key].checked = Boolean(value); else if (form.elements[key].type === 'datetime-local') form.elements[key].value = formatLocalInput(value); else form.elements[key].value = value || ''; }); } catch (error) { toast(error.message, 'error'); } }
async function submitSettings(event) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); ['registrationOpen','registrationClose','evaluationDate','presentationDate','finalResultDate'].forEach((key) => values[key] = new Date(values[key]).toISOString()); values.registrationEnabled = form.elements.registrationEnabled.checked; try { const data = await request('/api/admin/settings', { method: 'PUT', body: JSON.stringify(values) }); toast(data.message); } catch (error) { toast(error.message, 'error'); } }
async function loadActivity() { try { const data = await request('/api/admin/activity'); document.getElementById('activity-content').innerHTML = data.activity.map(activityItem).join('') || '<div class="empty-state"><strong>No activity yet</strong><span>Activity will appear here.</span></div>'; } catch (error) { toast(error.message, 'error'); } }

async function downloadFile(path, filename) { try { const response = await fetch(api(path), { headers: { Authorization: `Bearer ${token()}` } }); if (!response.ok) { const info = await response.json().catch(() => ({})); throw new Error(info.message || 'Could not generate the report.'); } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = Object.assign(document.createElement('a'), { href: url, download: filename }); document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (error) { toast(error.message, 'error'); } }

function bindStaticEvents() { document.querySelectorAll('#side-nav button').forEach((button) => button.addEventListener('click', () => changeView(button.dataset.view))); document.querySelectorAll('[data-go-view]').forEach((button) => button.addEventListener('click', () => changeView(button.dataset.goView))); document.getElementById('logout-button').addEventListener('click', () => { localStorage.removeItem('sih_token'); localStorage.removeItem('sih_user'); window.location.href = 'index.html'; }); document.getElementById('student-search-button').addEventListener('click', () => loadStudents()); document.getElementById('student-search').addEventListener('keydown', (event) => { if (event.key === 'Enter') loadStudents(); }); document.getElementById('export-team-list').addEventListener('click', () => downloadFile('/api/admin/exports/teams?format=xlsx', 'sih-team-list.xlsx')); document.getElementById('evaluation-form').addEventListener('submit', submitEvaluation); document.querySelectorAll('#evaluation-form input[type="number"]').forEach((input) => input.addEventListener('input', updateScoreTotal)); document.getElementById('refresh-ranking').addEventListener('click', loadRanking); document.getElementById('resource-form').addEventListener('submit', submitResource); document.getElementById('announcement-form').addEventListener('submit', submitAnnouncement); document.getElementById('settings-form').addEventListener('submit', submitSettings); document.getElementById('refresh-activity').addEventListener('click', loadActivity); document.querySelectorAll('.export-button').forEach((button) => button.addEventListener('click', () => downloadFile(`/api/admin/exports/${button.dataset.type}?format=${button.dataset.format}`, `${button.dataset.type}-report.${button.dataset.format}`))); }

async function initialise() {
  if (!token()) return window.location.replace('index.html');
  try { const data = await request('/api/auth/me'); currentUser = data.user; setUserChrome(); document.querySelectorAll('[data-admin-only]').forEach((item) => item.hidden = currentUser.role !== 'admin'); document.querySelectorAll('[data-student-only]').forEach((item) => item.hidden = currentUser.role !== 'student'); document.getElementById('student-overview').hidden = currentUser.role !== 'student'; document.getElementById('admin-overview').hidden = currentUser.role !== 'admin'; bindStaticEvents(); if (currentUser.role === 'student') { const [dashboard, publicData] = await Promise.all([request('/api/student/dashboard'), fetch(api('/api/public/config')).then((response) => response.json())]); studentData = { ...dashboard, problems: publicData.problemStatements || [] }; renderStudentOverview(); } else { await loadAdminDashboard(); } } catch (error) { console.error(error); if (token()) toast(error.message, 'error'); }
}
document.addEventListener('DOMContentLoaded', initialise);
